package org.wilson.world.task;

import org.wilson.world.manager.DiceManager;
import org.wilson.world.manager.NotifyManager;
import org.wilson.world.manager.TaskAttrDefManager;
import org.wilson.world.manager.TaskManager;
import org.wilson.world.model.Task;
import org.wilson.world.model.TaskAttr;

public class DemoTaskInteractor extends SystemTaskInteractor {
    public static final String SYMBOL = "demo";
    
    @Override
    public String getSymbol() {
        return SYMBOL;
    }

    @Override
    public void interact(Task task, String command) {
        if(!"end".equals(command)) {
            Task newTask = new Task();
            newTask.name = "Demo " + DiceManager.getInstance().randomName(15);
            newTask.content = "This is a task generated by [" + this.getClass().getCanonicalName() + "].";
            newTask.createdTime = System.currentTimeMillis();
            newTask.modifiedTime = newTask.createdTime;
            newTask.attrs.add(TaskAttr.create(TaskAttrDefManager.DEF_INTERACTOR, this.getSymbol() + ":end"));
            TaskManager.getInstance().createTask(newTask);
            
            NotifyManager.getInstance().notifySuccess(this.getClass().getSimpleName() + " created a task [" + newTask.name + "].");
        }
    }

}
